### ISSUE TITLE
why recall > 1

### ISSUE THREAD

**Issue by anyuzoey** [Britefury/py-bsds500#1]
Hi @Britefury 
thank you very much for your effort on transfer c to python. However, when I use this code to do the evaluation, I found out recall is larger than one, which is strange, do you know what might be the reason. I set the apply thin to be false.
Looking forward to your reply.

**Comment by Britefury** [comment]
Hi,
Sorry for my late reply.
Did you close the issue because you were able to resolve it, or it is a flaw in my code?

**Comment by anyuzoey** [comment]
Hi @Britefury

Thank you for your reply. I have resolve it. I'm using it in another dataset, and found out that the speed is highly related to the size of the input images. Thus, I resize them to a smaller size. This resize process make ground truth images contain pixels not just 0s and 1s. This is the reason that I got recall > 1.
BTW, thank you for your code. It's been a long time since my last MATLAB script, reading MATLAB code cause me headache. Your code save me a lot of time.
